name: Update README with latest blogs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */24 * * *" # Runs Every 24 Hours

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Fetch latest blogs from Dev.to"
        id: fetch_blogs
        run: |
          API_KEY=${{ secrets.DEVTO_API_KEY }}
          USERNAME="devshetty"
          BLOGS=$(curl -s "https://dev.to/api/articles?username=$USERNAME&per_page=3" -H "api-key: $API_KEY")
          echo "::set-output name=blogs::$BLOGS"

      - name: Update README
        run: |
          BLOGS="$GITHUB_WORKSPACE/${{ steps.fetch_blogs.outputs.blogs }}"
          BLOG_CONTENT="## Latest Blog Posts\n"
          for title in $(echo $BLOGS | jq -r '.[].title'); do
            url=$(echo $BLOGS | jq -r --arg title "$title" '.[] | select(.title == $title) | .url')
            BLOG_CONTENT+="\n- [$title]($url)"
          done
          sed -i "s|<!-- BLOGS-PLACEHOLDER -->|$BLOG_CONTENT|" README.md
